#ifndef BOREALOS_PS2CONTROLLER_H
#define BOREALOS_PS2CONTROLLER_H

#include <Definitions.h>
#include "Core/Firmware/ACPI.h"

#define PS2_DEVICE_RESET_SUCCESS_RESPONSE_1 0xFA
#define PS2_DEVICE_RESET_SUCCESS_RESPONSE_2 0xAA
#define PS2_CONTROLLER_TEST_SUCCESS 0x55
#define PS2_INTERFACE_TEST_SUCCESS 0x00
#define PS2_WRITE_TO_2ND_PORT_CMD 0xD4
#define PS2_CMD_STATUS_REGISTER 0x64
#define PS2_DEVICE_RESET_FAIL 0xFC
#define PS2_DUAL_CHANNEL_BIT 5
#define PS2_INBUF_CLEAR_BIT 1
#define PS2_DATA_REGISTER 0x60
#define PS2_TRX_TIMEOUT 1000000

Status PS2ControllerInit();

#endif //BOREALOS_PS2CONTROLLER_H